--- #YAML:1.0
name: Net-Flickr-API
version: 1.6
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: base API class for Net::Flickr::* libraries
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
