--- #YAML:1.0
name: Net-Flickr-API
version: 1.2
author:
  - Aaron Straup Cope E<lt>ascope@cpan.orgE<gt>
abstract: base API class for Net::Flickr::* libraries
license: perl
requires:
  Config::Simple: 0
  Flickr::API: '>= 0.07'
  Log::Dispatch: '>= 2.10'
  Readonly: 0
  XML::XPath: '>= 1.13'
build_requires:
  Test::Simple: '>= 0.47'
provides:
  Net::Flickr::API:
    file: lib/Net/Flickr/API.pm
    version: 1.2
generated_by: Module::Build version 0.2604
